# Generated by Django 3.1.6 on 2021-02-10 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('registrationNumber', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('contactDetails', models.TextField()),
                ('dateJoined', models.TextField(default='dd/mm/yyyy')),
                ('standsSold', models.IntegerField(default=0)),
                ('avaragePricing', models.TextField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationCode', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('photo', models.TextField()),
                ('idNumber', models.TextField()),
                ('dob', models.TextField()),
                ('gender', models.TextField()),
                ('profilePhoto', models.ImageField(upload_to='profiles/')),
                ('verified', models.BooleanField(default=False)),
                ('credit', models.TextField(default='ZWL$0,00')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stands',
            fields=[
                ('address', models.TextField(primary_key=True, serialize=False)),
                ('purchased', models.BooleanField(default=False)),
                ('price', models.TextField()),
                ('stage', models.TextField(default='Stands released')),
                ('image', models.ImageField(default='none.jpg', null=True, upload_to='standImages/')),
                ('information', models.TextField(default='No information is set here')),
                ('sitePlan', models.FileField(default='img/notset', upload_to='docs/sitePlan/')),
                ('measurements', models.TextField(default='200 square metres')),
                ('datePosted', models.TextField(default='dd/mm/yyyy')),
                ('developer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lands.developer')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lands.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='standImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='standImages/')),
                ('datePosted', models.TextField(default='mm/dd/yyyy')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lands.stands')),
            ],
        ),
    ]
