# Generated by Django 3.1.6 on 2021-02-08 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificationCode', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('photo', models.TextField()),
                ('idNumber', models.TextField()),
                ('dob', models.TextField()),
                ('gender', models.TextField()),
                ('profilePhoto', models.ImageField(upload_to='profiles/')),
                ('verified', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stands',
            fields=[
                ('address', models.TextField(primary_key=True, serialize=False)),
                ('purchased', models.BooleanField(default=False)),
                ('price', models.TextField()),
                ('stage', models.TextField(default='Stands released')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lands.userdata')),
            ],
        ),
    ]
