# Generated by Django 3.1.6 on 2021-03-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(default='head')),
                ('body', models.TextField(default='body')),
                ('new', models.TextField(default='more')),
            ],
        ),
        migrations.CreateModel(
            name='leases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreementCode', models.IntegerField(auto_created=True)),
                ('dateIssued', models.TextField(default='dd/mm/yy')),
                ('dateSigned', models.TextField(default='dd/mm/yyyy')),
                ('governementLaw', models.TextField(default='Zimbabwe: Real Estate Laws and Regulations')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lands.developer')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lands.stands')),
            ],
        ),
    ]
