# Generated by Django 3.1.6 on 2021-02-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='datePosted',
            field=models.TextField(default='dd/mm/yyyy'),
        ),
        migrations.AddField(
            model_name='stands',
            name='developer',
            field=models.TextField(default='Mopold Holdins'),
        ),
        migrations.AddField(
            model_name='stands',
            name='information',
            field=models.TextField(default='No information is set here'),
        ),
        migrations.AddField(
            model_name='stands',
            name='measurements',
            field=models.TextField(default='200 square metres'),
        ),
        migrations.AddField(
            model_name='stands',
            name='sitePlan',
            field=models.FileField(default='img/notset.pdf', upload_to='docs/sitePlan/'),
        ),
    ]
