# Generated by Django 3.1.6 on 2021-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='credit',
            field=models.TextField(default='ZWL$0,00'),
        ),
    ]
