# Generated by Django 3.1.6 on 2021-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0002_auto_20210209_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stands',
            name='sitePlan',
            field=models.FileField(default='img/notset', upload_to='docs/sitePlan/'),
        ),
    ]
