# Generated by Django 3.1.6 on 2021-02-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0002_auto_20210208_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
