# Generated by Django 3.1.6 on 2021-02-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0003_userdata_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='stands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('purchased', models.BooleanField(default=False)),
                ('price', models.TextField()),
                ('stage', models.TextField(default='Stands released')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lands.userdata')),
            ],
        ),
    ]
