# Generated by Django 3.1.6 on 2021-03-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0003_auto_20210301_0445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feeds',
            new_name='feed',
        ),
    ]
