# Generated by Django 3.1.6 on 2021-02-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0005_auto_20210208_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stands',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stands',
            name='owner',
        ),
        migrations.AddField(
            model_name='userdata',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stands',
            name='address',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.TextField(default='not set'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='verificationCode',
            field=models.TextField(),
        ),
    ]
