# Generated by Django 3.1.6 on 2021-02-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lands', '0006_auto_20210208_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='stands',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Lands.userdata'),
        ),
    ]
